-- Generated from generator/demo_specs/aws-malaysia-palm-oil-traceability.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-malaysia-palm-oil-traceability
-- This is the schema that is actually deployed for MY_PALM_OIL_TRACEABILITY.

-- Alerts fire on the bottom tail of TTP Coverage
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_TTP_COVERAGE) AS T
  FROM RAW.CHAIN_OF_CUSTODY
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_TTP_COVERAGE <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_TTP_COVERAGE), 2) AS AVG_TTP_COVERAGE,
  ROUND(AVG(f.KPI_MSPO_CERTIFIED), 2) AS AVG_MSPO_CERTIFIED,
  ROUND(AVG(f.KPI_DATA_COMPLETENESS), 2) AS AVG_DATA_COMPLETENESS
FROM RAW.CHAIN_OF_CUSTODY f
JOIN RAW.BUYERS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_TTP_COVERAGE), 2) AS AVG_TTP_COVERAGE,
  ROUND(AVG(f.KPI_MSPO_CERTIFIED), 2) AS AVG_MSPO_CERTIFIED,
  ROUND(AVG(f.KPI_DATA_COMPLETENESS), 2) AS AVG_DATA_COMPLETENESS
FROM RAW.CHAIN_OF_CUSTODY f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_TTP_COVERAGE) AS KPI_TTP_COVERAGE, AVG(KPI_MSPO_CERTIFIED) AS KPI_MSPO_CERTIFIED, AVG(KPI_DATA_COMPLETENESS) AS KPI_DATA_COMPLETENESS FROM RAW.CHAIN_OF_CUSTODY),
     en AS (SELECT SUM(KPI_SMALLHOLDERS_TRACED) AS KPI_SMALLHOLDERS_TRACED, SUM(KPI_MILLS_MONITORED) AS KPI_MILLS_MONITORED, SUM(KPI_COLLECTION_POINTS) AS KPI_COLLECTION_POINTS, SUM(KPI_GPS_MAPPED_PLOTS) AS KPI_GPS_MAPPED_PLOTS FROM RAW.BUYERS)
  SELECT 1 AS SORT_ORDER, 'TTP Coverage' AS TITLE, KPI_TTP_COVERAGE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_TTP_COVERAGE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'MSPO Certified' AS TITLE, KPI_MSPO_CERTIFIED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_MSPO_CERTIFIED)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Smallholders Traced' AS TITLE, KPI_SMALLHOLDERS_TRACED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_SMALLHOLDERS_TRACED) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Mills Monitored' AS TITLE, KPI_MILLS_MONITORED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_MILLS_MONITORED)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Collection Points' AS TITLE, KPI_COLLECTION_POINTS AS VALUE_NUM, LTRIM(TO_VARCHAR(CAST(ROUND((KPI_COLLECTION_POINTS)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'GPS-Mapped Plots' AS TITLE, KPI_GPS_MAPPED_PLOTS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_GPS_MAPPED_PLOTS) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Data Completeness' AS TITLE, KPI_DATA_COMPLETENESS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DATA_COMPLETENESS)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
