-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Supply Chain Traceability
-- ============================================================================
USE DATABASE PALM_OIL_TRACEABILITY;
USE SCHEMA ML;

-- ML.ANOMALY_DETECTION: MASS_BALANCE_ANOMALY_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.MASS_BALANCE_ANOMALY_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.MASS_BALANCE_RECONCILIATION'),
  SERIES_COLNAME => 'MILL_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.MASS_BALANCE_ANOMALY_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.MASS_BALANCE_ANOMALY_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.MASS_BALANCE_RECONCILIATION'), SERIES_COLNAME => 'MILL_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

