-- ============================================================================
-- 99_RESET.SQL — Reset Supply Chain Traceability to clean demo state
-- ============================================================================
USE DATABASE PALM_OIL_TRACEABILITY;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_REFRESH_CHAIN SUSPEND;
ALTER TASK IF EXISTS APP.TASK_RECONCILE_MASS_BALANCE SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_ICEBERG SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.FULL_CHAIN_OF_CUSTODY REFRESH;
ALTER DYNAMIC TABLE CURATED.MILL_TRACEABILITY_SCORE REFRESH;
ALTER DYNAMIC TABLE CURATED.BUYER_SUPPLY_CHAIN_VIEW REFRESH;
ALTER DYNAMIC TABLE CURATED.MASS_BALANCE_RECONCILIATION REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM PALM_OIL_TRACEABILITY.RAW.MILLS → 100
-- SELECT COUNT(*) FROM PALM_OIL_TRACEABILITY.RAW.CHAIN_OF_CUSTODY → 50000
-- SELECT COUNT(*) FROM PALM_OIL_TRACEABILITY.RAW.SHIPMENTS → 20000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_REFRESH_ICEBERG RESUME;
ALTER TASK IF EXISTS APP.TASK_RECONCILE_MASS_BALANCE RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_CHAIN RESUME;
